#
# Copyright © 2017 Mathieu Carbou (mathieu.carbou@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

theme: jekyll-theme-dinky
title: Megatron
show_downloads: true
google_analytics: UA-5669052-12
plugins:
  - jekyll-asciidoc
github:
  zip_url: https://github.com/mathieucarbou/megatron/releases
  tar_url: https://github.com/mathieucarbou/megatron/releases
